### ISSUE TITLE
As of 3/17/2019, API endpoint seems to have changed, API Key error is received

### ISSUE THREAD

**Issue by BearInTexas** [natekspencer/LitterRobotManager#4]
It looks like Litter Robot moved to an AWS-based endpoint.  All integrations using this Litter Robot code no longer work.  It should be updated to work with LR's new endpoint.

**Comment by natekspencer** [comment]
I release a new version of the SmartApp that should hit the new endpoints. If you have the old apiKey set in the SmartApp settings, you'll want to make sure you remove those otherwise it will try to use that and fail.
